name: Go
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout {{ github. }}
        uses: actions/checkout@v4.1.7

      - name: Set up Go project
        uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.23.1'
      - name: Build Go project
        run: go build -o zen
