name: Go
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4.1.7

      - name: Set up Go project
        uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.23.1'
      - name: Build ${{ github.repository }} project
        run: go build -o zen

      - name: Upload to artifact
        uses: actions/upload-artifact@v4.4.0
        with:
            name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-binaries
            path: ./zen
